apiVersion: v1
kind: Secret
metadata:
  name: safemotos-secrets
type: Opaque
data:
  databaseUrl: bW9uZ29kYjovL2FwaUFkbWluVXNlcjpOenQ3UVJNazROOEVKL01zaFNoYndnPT1AU0ctTW9uZ29Qcm9kdWN0aW9uLTEyMTcyLnNlcnZlcnMubW9uZ29kaXJlY3Rvci5jb206MjcwMTcsU0ctTW9uZ29Qcm9kdWN0aW9uLTEyMTczLnNlcnZlcnMubW9uZ29kaXJlY3Rvci5jb206MjcwMTcsU0ctTW9uZ29Qcm9kdWN0aW9uLTEyMTc0LnNlcnZlcnMubW9uZ29kaXJlY3Rvci5jb206MjcwMTcvc3RlbXBsYXRlP3JlcGxpY2FTZXQ9UlMtTW9uZ29Qcm9kdWN0aW9uLTAK
  redisServer: c2ctcmVkaXNkYi0yMTUtbWFzdGVyLnNlcnZlcnMubW9uZ29kaXJlY3Rvci5jb20K
  redisPass: cGQ3eDdObTV5SEtUcmpDbVMwNnhJN1dPb0JHNFNHVnYK
  redisPort: NjM3OQo=