swagger: '2.0'
info:
  version: 1.0.0
  title: service-template
basePath: /api/v1
paths:
  /Vitals:
    get:
      tags:
        - Vital
      summary: do health check
      operationId: Vital.check
      parameters: []
      responses:
        '200':
          description: Request was successful
          schema:
            description: health check
            type: object
      deprecated: false
tags:
  - name: Vital
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - application/xml
  - text/xml
produces:
  - application/json
  - application/xml
  - text/xml
  - application/javascript
  - text/javascript
definitions: {}
